### ISSUE TITLE
refactor to use management-api

### ISSUE THREAD

**Issue by goern** [thoth-station/init-job#27]
**Is your feature request related to a problem? Please describe.**
We provide a management api endpoint to register new python indices, this should be used by init-job

**Describe the solution you'd like**
something that is not using the graph database directly

**Describe alternatives you've considered**
none.

**Additional context**
be a better microservice user.

**Comment by goern** [comment]
@pacospace do we need this?!

**Comment by pacospace** [comment]
Not really, init-job already has a way to register indices. https://github.com/thoth-station/init-job/blob/7e0e85f88a21cfcb1d76dafeec9acc955020ac0b/app.py#L192.

**Comment by pacospace** [comment]
Or do we want to have those functions in mangament-api? and init-job use the endpoint in management-api when it has to register the known indices?

**Comment by goern** [comment]
is this done?!

@fridex @pacospace

**Comment by fridex** [comment]
I would not do it this way. As init-job is triggered on a fresh deployment, we would rely on management-api being up. it authentication management etc. It feels cleaner to me having this implemented as it is now.
