### ISSUE TITLE
Add intel TF builds to knowledge graph [3pt]

### ISSUE THREAD

**Issue by goern** [thoth-station/init-job#385]
add the intel TF builds to our knowledge graph, so that we can run Amun inspections and generate PI for them.

seeAlso https://software.intel.com/content/www/us/en/develop/articles/intel-optimization-for-tensorflow-installation-guide.html#pip_wheels

**Comment by fridex** [comment]
We have already analyzed it and it is ready for performance analysis.

**Comment by goern** [comment]
cool! how can we show that off in a small demo?

**Comment by fridex** [comment]
Let's try to do some perf analysis and we can plug a pipeline unit that recommends intel/aicoe/upstream TF based on our observations.

**Comment by fridex** [comment]
Is the demo relevant here?

**Comment by goern** [comment]
@fridex what is the state here?!
/priority backlog

**Comment by fridex** [comment]
We already monitor intel-tensorflow releases. Also, we do advises for specific hardware:

https://github.com/thoth-station/prescriptions/blob/7e938ffa4bbb7aae498f89e4c293e6ae7de300d8/prescription.yaml#L754-L773

Also, as an alternative to tensorflow or tensorflow-cpu:

https://github.com/thoth-station/prescriptions/blob/7e938ffa4bbb7aae498f89e4c293e6ae7de300d8/prescription.yaml#L21-L50

/close
