### ISSUE TITLE
Relax solver rules

### ISSUE THREAD

**Issue by fridex** [thoth-station/init-job#425]
**Describe the bug**

With solver rules installed, we are able to reduce number of packages analyzed. However, the current configuration is too strict. Currently, we limit packages to yunger than 5 years. This leads to resolver issues with some stacks. For example, the latest [termcolor](https://pypi.org/project/termcolor/#history) dates back to Jan 2011 so we disabled it based on solver rules. This leads to issues as packages still use it (e.g. tensorflow).

**Comment by goern** [comment]
/triage needs-information

Hey @fridex is this something longterm? Or does is just need some investigation and a proposal for new rules?

/kind feature

**Comment by fridex** [comment]
This tightly corresponds to https://github.com/thoth-station/thoth-application/issues/1514 and reasons mentioned in [the last demo](https://www.youtube.com/watch?v=wjMNOyGupbs). Basically, we could reuse statistics about packages used (either in thoth, communities such as fedora, ...) and let the system analyze just these. This way, the system converges to a state when we analyze packages that are really used and we can use hardware to aggregate other data.

Linking github statistics done by @xtuchyna to packages based on https://github.com/thoth-station/core/issues/286 can give also more insights about package community (e.g. whether the given project has still active community and such -- if not, thoth will not analyze it and also not recommend).

**Comment by goern** [comment]
/remove-lifecycle rotten

@fridex could you please outline a solution/implementation?

**Comment by fridex** [comment]
> @fridex could you please outline a solution/implementation?

See the demo - https://www.youtube.com/watch?v=wjMNOyGupbs

Basically, we should make sure the system has packages that are used by users and required. If we analyze too many packages, the system is overloaded with analysis and package updates. If we analyze only few packages, the system is not serving user requests correctly (missing packages). The solution is to find the right balance - that's why we started ingestion with a minimal set of packages in stage (packages we know are used).

**Comment by xtuchyna** [comment]
@fridex do we plan to do smthg with this furthermore?

**Comment by fridex** [comment]
> @fridex do we plan to do smthg with this furthermore?

Yes, the system needs to be configured to analyze packages that teams are interested in. Based on that, configure solver rules in the deployment. So the subsequent step is to collect information about packages used in AICoE organization and ask for an advise.

**Comment by fridex** [comment]
I think we could close this one as there is no real immediate work to do as of now. It is more about observing which packages could be also ingested based on community use.

/close
